### ISSUE TITLE
Question about vga pin out 

### ISSUE THREAD

**Issue by Link040188** [jeffqchen/DC2VGA#1]
I assume that when using for an rgb set that the sync is on pin 13. But I could not find documentation confirming that or that the vga is wired to the vga standard. Again I assume this is right but I just wanted to double check. Before I wire up a scart connector to one end of a vga cable.

**Comment by jeffqchen** [comment]
Your guess is right. However you don't have to cut up a VGA cable. You can build another one of my adapter to easily hoot it up to SCART:
https://github.com/jeffqchen/VGAxSCART

**Comment by Link040188** [comment]
Wouldn’t I need to put some capacitors and a resistor in the scart connector or does the dc2vga handle that?

**Comment by jeffqchen** [comment]
The DC2VGA dongle is console-specific. It already contains all necessary components required for the signals. There is no need to add more.

**Comment by Link040188** [comment]
Thank you that saves me from using up unessesary caps
